# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  configs:
    uses: LouisBrunner/.github/.github/workflows/lint-configs.yml@main
